### PR TITLE
Implemented wcsdup. Fixes issue #118

### PR DESCRIPTION
**Pull request by josch1710**
Implemented function wcsdup.
This fixes issue #118 .
I didn't implement any tests, because I don't understand the test framework.

### CODE REVIEW

**Comment by SilvanScherrer** [comment]
It seems you messed with crlf vs lf in wchar.h.
Please fix it. As else rhe merge would break history.

**Comment by josch1710** [comment]
I fixed the line endings.

**Comment by dmik** [comment]
Thanks for your effort however I have to decline this pull request because our wchar functions are FreeBSD based and should come from there, not from GLibc. I imported the necessary FreeBSD source within #118.

**Comment by josch1710** [comment]
It's fine. I just went with Silvan's lead. Most important thing is, that the gap is closed ;-)

**Pull request closed without merging**
